services:
    wordpress:
        build:
            context: .
        volumes:
            - wordpress-files:/var/www/html
        environment:
            SERVICE_URL_WORDPRESS: ${SERVICE_URL_WORDPRESS:-}
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${SERVICE_USER_WORDPRESS:-wordpress}
            WORDPRESS_DB_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS:-wordpress}
            WORDPRESS_DB_NAME: wordpress
        depends_on:
            mysql:
                condition: service_healthy
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://127.0.0.1
            interval: 2s
            timeout: 10s
            retries: 10
        restart: always

    mysql:
        image: mysql/mysql-server:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_ROOT:-rootpass}
            MYSQL_DATABASE: wordpress
            MYSQL_USER: ${SERVICE_USER_WORDPRESS:-wordpress}
            MYSQL_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS:-wordpress}
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            interval: 5s
            timeout: 20s
            retries: 10
        restart: always

volumes:
    wordpress-files:
    mysql-data:
